#!/bin/bash

if [ "$0" != "./docker/docker-update" ]; then
    echo "Error must run this command from CPP directory using docker/docker-update"
    exit 
fi

d=$(date +"%Y_%m_%d")

echo "creating docker container running shinyCPP"
id=`docker run -td gdancik/cpp`
echo "container id is $id" 

echo "deleting /root/CPP/* from container"
docker exec $id rm -Rf /root/CPP/*

echo "adding local CPP/ to /root/CPP"
docker cp CPP $id:/root/

echo "saving image as gdancik/cpp:$d"
docker commit $id gdancik/cpp:$d

echo "stopping docker container $d"
docker stop $id

